#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <conio.h>
#include <windows.h>
#include <locale.h>
#include <stdbool.h>

#include "init.h"
#include "logo.h"
#include "telaInicial.h"
#include "login.h"
#include "loginAnalista.h"
#include "menuPrincipal.h"
#include "menuPrincipalAnalista.h"
#include "investidorNivel.h"
#include "menuAnalista.h"
#include "cadastroAnalista.h"
#include "menuClientes.h"
#include "cadastroClientes.h"
#include "sair.h"
